### ISSUE TITLE
0.0.4.1 breaks pulverizing sand to dust recipe (ex. nihlo / thermal expansion)

### ISSUE THREAD

**Issue by Duckle29** [Toops/TinkersSteelworks#23]
Tested on agrarian skies. Upgrading from 0.0.3 made ducts work properly, however version 0.0.4.1 breaks the recipie to pulverize sand into dust in pulverizers.

Playing on agrarian skies, with manually replaced Tsteelworks version. Tsteelwork 0.0.4 works just fine.

**Comment by wisthy** [comment]
I saw during my test that all the Ex-Nihilo meltable things are not compatible with the High Oven except for the "dust" final stage. 

But I didn't remember if it was working on 0.0.3. It was already on my todo list to check that. If Toops doesn't fix it before I finish the two issues I'm working on, I'll investigate that.

**Comment by Duckle29** [comment]
This is not an issue with smeltables :) we have a line that converts the dust and such into the final stage blocks. The issue is that putting sand into a pulverizer, will not do anything. I also noticed that an adjacent pulverizer will not output sand into another pulverizer, tho the sand can be placed in a pulverizer manually, again not doing anything. 

EDIT: If you have any idea of where the problem might be, I'll start snooping around in the source to see for myself. I've wanted to look at minecraft mods for a while :)

**Comment by wisthy** [comment]
So, to be sure I understand you, when you replace the version of this mod in Agrarian Skies and only this mod some recipes from another mods are removed.

It sounds strange to me. I know it's possible to remove recipe from another mod but I don't think we can do that accidently. But one way or another, it should be something in the recent commits.

**Comment by Duckle29** [comment]
Hmm I'll put it in bullet form. Everything is better in bullet form.
- Running stock Agrarian skies means ducts doesn't work (TConstruct 0.0.3)
- Replacing TConstruct 0.0.3 with TConstruct 0.0.4.1 makes ducts work properly, however putting sand in the thermal expansion pulverizers does nothing (Pulverizer just does nothing) 
  Another weird bug is that a pulverizer(1) adjacent to another pulverizer(2), set to output into the adjacent pulverizer(2 -> 1) will not do anything either, you can however place sand in the pulverizer manually, but that as mention doesn't start the pulverizer.

[Github markdown to indent not working] Also NEI still reports the recipe, but it doesn't work
- Replacing TConstruct 0.0.4.1 with 0.0.4 fixes these issues, and is what we currently work with.

As a note, I see "-Forgot to fix Thermal Expansion slag output :3" as the know caveat on the 0.0.4.1 so it sounds like you might be in TE, so some mistake in there? :P

**Comment by wisthy** [comment]
Let's check the diff between 0.0.4.1 and 0.0.4

The fix for the slag output is just to replace a "x <= 15" by a "x <=10" so obviously, it's not that. I'm searching for the other modification made between 0.0.4 and 0.0.4.1

**Comment by wisthy** [comment]
Nothing found so far that can explain something like that.

**Comment by Duckle29** [comment]
Can you replicate it?

**Comment by Toops** [comment]
Hmmm, for slag output, I changed the way it determines whether an item is an ore or not by searching 'startswith("ore")' for the oreDictionary name. Console tests passed, but something else went silly somewhere. 

Onto the larger issue; it's almost certainly an issue with the OreDictionary I'm sure. One such change I made is moving the oredict registry and the high oven's specialized smelting (steel, scorched bricks, nether quartz) registry to postInit, which later I was advised not to do, so there's that to look into - on the flip side, the previous way caused those entries to fail to work. This is probably due to differing name conventions. For example, Thermal Expansion registers coal (item) as simply 'coal', while many agree it should be 'fuelCoal' - so for good measure, I had registered it as both. Similarly, I register vanilla sand as 'blockSand' (seems reasonable, no?), but I have the suspicion this may be getting overridden or is overriding other entries. So, I think I'll take another stab at this by dropping the ore registry back to Init, and investigate what other mods are doing with their oreDict names - especially TE and ExN.

EDIT: Just noticed you'd assigned it, wisthy, so I'll see what you come up with unless you'd rather let me handle it.

**Comment by wisthy** [comment]
I assigned it to me but I havn't found anything usefull yet. You seems to know where to look which is not my  case. I assigned it back to you.

**Comment by wisthy** [comment]
Tested just now in 0.0.4.1

I confirm I have the same issue. I can pulverise cobble into gravel, gravel into sand but sand is not recognized by the pulveriser. 

http://imgur.com/ohm8vj0

Same test in 0.0.4

sand is processed correctly but waila still indicate it with OreDictionary name SandBlock.

In summary, I confirm I have the exact same behavior as described by dumle29.

**Comment by Toops** [comment]
Fixed as of 0.0.4.2
Thanks for the report!
