### ISSUE TITLE
tag version

### ISSUE THREAD

**Issue by wisthy** [Toops/TinkersSteelworks#25]
Toops, 

In order to help investigate issue, I suggest to use release tag everytime we build a new version in order to be able to know precisely what is included in each version.

**Comment by Toops** [comment]
Agreed! I read something about that once, but forgot to do further research as to how to implement it. It's about time for me to actually learn how to github properly. Further, I'd like to figure out how @VERSION@ and the such works, because I have a tenancy to forget to update both the Repo.java and mcmod.info versions.

Research time~

Any further related suggestions are expressly welcome. :)

**Comment by Toops** [comment]
Tags are now a thing~
Thanks wisthy

**Comment by wisthy** [comment]
I've found that: http://nvie.com/posts/a-successful-git-branching-model/

It sounds good to me. I suggest to adopt it.

**Comment by Toops** [comment]
I like that. I've delayed responding lately because I had to take a little break, and I'm still really shaky on all these gitisms. After reading up on this development model though, I can appreciate how well-organized and professional it truly is. The only thing is that it's a bit late in the game to start adopting a system like this, when I plan on beginning direct integration into TConstruct sometime around or shortly after 0.0.5. However, I believe TConstruct itself could greatly benefit from this, so I believe once we're at that point, I'll suggest it. That said, having a develop branch for TSteelworks as it exists now is a splendid idea.

**Comment by wisthy** [comment]
As it's not costy to switch or GIT process model, I think we can adopt it even if the project has only a few months left to live on its own before behing merged into TC.

I'm testing other stuff like that. I configured a jenkins yesterday to build the project automatically from GIT. It will check every hours if something has changed on the develop branch on my fork and build it (through ant) if necessary. I still have to find out how to "publish" the generated jar. After that, the next step is to try to launch sonar (static scan of the code to find bad practices) automatically. And maybe investigate about a way to add some JUnit in the project (NBT reader, validation, ...)
